declare const styles: {
    readonly button_icon_danger: string;
    readonly button_primary: string;
    readonly code_callable: string;
    readonly code_chip: string;
    readonly code_container: string;
    readonly code_content: string;
    readonly code_empty: string;
    readonly code_function: string;
    readonly code_header: string;
    readonly code_line_number: string;
    readonly code_parameter: string;
    readonly code_preview: string;
    readonly code_symbol: string;
    readonly code_variable: string;
    readonly donate: string;
    readonly editable_code_chip: string;
    readonly main_grid: string;
    readonly resize_handle: string;
};
export = styles;
